from ControlCharts.ControlCharts import ControlCharts
from Normality.NormalityTests import NormalityTests
from Relationship.Correlation import CorrelationTest
from Relationship.Association import AssociationTest
from Difference.Difference import DifferenceTest